:path: chemie/
:imagesdir: img/
:plantumlsdir: puml
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]
= 4. Generierung von zufallsbasierten Molekülen

== 4.1 Aufgabenbeschreibung

Die Aufgabe war es einen Algorithmus zu entwickeln, der zufällige Atome aus dem Periodensystem auswählt und diese unter Einhaltung der chemischen Regeln miteinander verbindet, so dass am Ende ein Molekül entsteht, das aus zufälligen Atomen besteht. Das endgültige Ziel ist dabei, diese Moleküle in Aufgaben für Studierende zu integrieren. Diese Aufgaben könnten dann zum Beispiel sein: Ein Teil des Moleküls wird entfernt und die Studierenden müssen den fehlenden Teil ergänzen oder es ist ein Molekül gegeben und dazu soll der Name angegeben werden.

=== 4.1.1 Einschränkungen der Regeln

Mir wurde relativ zeitig bewusst, dass die vorhandene Zeit für die Entwicklung eines so komplexen Algorithmus nicht ausreichen wird. Deshalb haben wir (Professor & Ich) uns auf ausgewählte Regeln geeinigt. Der Algorithmus soll vorerst mit Kohlenstoff, Wasserstoff und Sauerstoff Atomen arbeiten. Von diesen drei Atomen wird, sobald ein Atom generiert wird, eins zuällig ausgewählt. Die Wahrscheinlichkeiten für die Auswahl sind dabei unterschiedlich: für Wasserstoff 50%, Sauerstoff und Kohlenstoff 25%. Die Anzahl der vorliegenden Bindungen zwischen den einzelnen Atomen sollen zufällig sein. Dies geschieht unter Einhaltung der Valenz. Die in dem Algorithmus auch das Hauptkriterium bildet, denn am Ende soll ein Molekül generiert werden, dass keine offenen Bindungen mehr aufweist.


== 4.2 Umsetzung

Bei der Umsetzung des Algorithmus habe ich auf die Sprache Python gesetzt. Unter Verwendung von Visual Studio Code mit Jupyter Notebook und Google Colab habe ich ihn entwickelt. 
Als erstes habe ich die Klasse 'Atom' erstellt mit allen Attributen die gebraucht werden, z.B. Valenz und Formel. Zusätzlich sind die Nachbar Atome eines Atoms in einem Dictionary gespeichert. Dazu gibt es noch die drei Unterklassen der jeweiligen Atome, die eine Instanz der Superklasse (Atom) mit den passenden Werten erzeugen. Zusätzlich habe ich die Funktionen mit denen man die Valenz und auch die Anzahl der freien Bindungen eines Atoms ausgegeben bekommt implementiert. Dazu kommen die beiden Funktionen mit denen Nachbarn hinzugefügt und entfernt werden können, damit diese in dem Dictionary des jeweiligen Nachbarn gespeichert oder entfernt werden können.

Der Nutzer kann am Anfang eingeben wie viele Atome ein Molekül enthalten soll (Variable: n) und wie viele Moleküle der Alogrithmus berechnen und ausgeben soll.
Das Molekül ist am Anfang ein leerer Array (M). Danach wird durch die Funktion 'choose_atom()' zufällig eine Instanz aus den Klassen Kohlenstoff, Sauerstoff und Wassserstoff initiiert  (Variable: a). Da die Atome unterschiedlich oft in der Realität vorkommen habe ich die Wahrscheinlichkeiten wie folgt festgelegt: Kohlenstoff 50%, Wasserstoff und Sauerstoff jeweils 25%. Daraufhin wird a zu M hinzugefügt. Nun besteht das Molekül theoretisch aus einem Atom. + 
Solange die Anzahl der Atome im Molekül (M) kleiner ist als die gewünschte Anzahl an Atomen (n) ist: M < n wird folgendes ausgeführt: +
Das Molekül wird nach Atomen mit freien Bindungen abgesucht und diese Atome werden gespeichert. Von diesen Atomen wird zufällig eines ausgewählt und es wird ein neues Atom durch 'choose_atom()' erzeugt(Variable: b), das ausgewählte und das neu erzeugte Atom wird über k Bindungen verknüpft. k ergibt sich aus einer Zufallszahl die zwischen 1 und dem Minimum von der freien Valenz von a oder der Valenz von b liegt. 

Kurzes Beispiel: a hat 2 freie Bindungen und b eine Valenz von 4. Dann würde k bei 1 oder 2 liegen. Also würden beide Atome mit 1 oder 2 Bindungen verknüpft werden.

Bei beiden Atomen wird der jeweilige neue Nachbar im Dictionary mit der Anzahl der Bindungen gespeichert.
Danach wird b auch zu M hinzugefügt. Nun befinden sich schon zwei Atome im Molekül. Diese können aber trotzdem noch freie Bindungen aufweisen.
Im nächsten Schritt wird geschaut ob beide Fälle gleichzeitig eintreffen: Die Anzahl der Atome im Molekül ist kleiner als die gewünschte Anzahl und kein Atom aus M weißt freie Bindungen auf. In dem Fall könnte kein neues Atom mehr hinzugefügt werden, da kein Atom mehr weitere Bindungen eingehen kann. Nun werden vorhandene Bindungen gelöst. Es wird ein Atom ausgewählt, dass nur mit genau einem anderen Atom verbunden ist. Zwischen diesen beiden Atomen werden dann (Zufallszahl zwischen 1 und vorhandenen Bindungen(k)) gelöst. Dabei kann es passieren, dass zufällig alle Bindungen zwischen den Atomen entfernt werden. Dann würde das Atom, welches ursprünglich nur zu einem Atom verbunden war aus dem Molekül entfernt werden. Hier beginnt die Schleife (Solange M < n) von vorn: Es wird wieder eine Instanz der Klasse C,H oder O erzeugt und über k Bindungen mit einem zufällig ausgewählten Atom verbunden..

Sobald die Schleife vollständig durchlaufen ist haben wir ein Molekül, dass die gewünschte Anzahl an Atomen besitzt (M = n), aber eventuell noch freie Bindungen aufweist.
Diese müssen jetzt noch befriedigt werden.

Dabei geht der Algorithmus wie folgt vor: Es werden alle Atome mit freien Bindungen in einem Array gespeichert. Dazu wird zufällig ein Atom aus dem Array ausgewählt und in einem anderen Array alle Nachbarn des ausgewählten Atoms (welches freie Bindungen aufweist) gespeichert. Zwischen dem ausgewählten Atom und einem zufällig ausgewählten Nachbarn werden jetzt die Bindungen (um das Minimum von den freien Bindungen beider Atome) erhöht. Die geschieht in der Funktion 'bindungen_erhöhen'.

Wieder ein kurzes Beispiel: Ausgewähltes Atom hat 2 freie Bindungen und ausgewählter Nachbar hat 3 freie Bindungen -> Bindungen zwischen beiden werden um 2 erhöht.

Nun sind schon einige Bindungen mehr befriedigt. Trotzdem kann es sein, dass sich immernoch Atome mit freien Bindungen im Molekül befinden.

Dann wird auf Variante 2 zugegeriffen: Es wird ein zufälliges Atom mit freien Bindungen aus dem Molekül ausgewählt (a) und es wird d berechnet. +
d wird wie folgt berechnet:

d = (Valenz von a) - (freie Bindungen von a)

Wenn die Zahl d der Valenz von Kohlenstoff, Sauerstoff oder Wasserstoff entspricht dann wird die Funktion atom_ersetzen() mit dem Namen des passenden Atoms als Prameter aufgerufen.

Dabei wird eine Instanz von dem passenden Atom erzeugt. Von dem zu ersetzendem Atom werden alle Nachbarn mit ihren Bindungen gespeichert und auf die neue Instanz übertragen. Das ausgewählte Atom wird dann aus dem Molekül entfernt und das neue nimmt seinen Platz ein.

Wenn d nicht zu einer Valenz der drei Atome passt dann gibt es folgende "Notlösung": Es werden d Wasserstoffatome an das ausgewählte Atom angehangen dies wird durch die Funktion '_wasserstoff_anhängen()_' realisiert.

Nun hat der Algorithmus ein Molekül erzeugt, dass keine freien Bindungen mehr aufweist. Jetzt muss es nur noch dargstellt werden.

Für die Darstellung habe ich folgende Python-Bibliotheken verwendet: PubChemPy, RDKit und Py3Dmol

Für die Ausgabe wird als erstes der SMILES Code (Darstellung des Moleküls als ASCII Code) zu dem erzeugten Molekül in der Funktion '_SMILES_Code()_' berechnet. Dazu habe ich folgendes als Hilfe genutzt: https://stackoverflow.com/questions/51195392/smiles-from-graph dies ermöglicht es einen SMILES Code von einem Graphen zu berechnen, deswegen wird in der Funktion 'create_adjacency_matrix()' das Molekül als Adjazenzmatrix dargestellt und dann an die Funktion 'MolFromGraphs()' weitergegeben. Mit dem Ergebnis von 'MolFromGraphs()' als Parameter für die RDKit-Bibliothek vorgegebe Funktion 'Chem.MolToSmiles ()' wird jetzt der SMILES Code berechnet. Der SMILES Code wird nun in Verbindung mit der PubChemPy Bibliothek genutzt. In der Funktion 'get_from_PubChem()' wird nun die Datenbank nach dem SMILES Code abgesucht und dadurch kann der Name und die Formel des Moleküls ausgegeben werden. +
Als letztes erfolgt die Ausgabe der 3D-Ansicht des Moleküls durch die FUnktion '_show()_'. Der Funktion wird der SMILES Code als Parameter übergeben. py3Dmol stellt hier einige Funktionen bereit mit denen Einstellungen an der 3D-Ansicht vorgenommen werden können. z.B. '_view()_' mit der ich die Größe der Ausgabe auf 600x600 beschränkt habe.



== 4.3 Probleme


== 4.4 Ausblick


